### ISSUE TITLE
How do I turn fake_A and fake_B into images and save them?

### ISSUE THREAD

**Issue by rbunn80110** [tmabraham/UPIT#16]
I would like to see what fake_A and fake_B look like at this step in the process saved as images.  I can't seem to figure out how to convert them properly.

def forward(self, output, target):
            """
            Forward function of the CycleGAN loss function. The generated images are passed in as output (which comes from the model)
            and the generator loss is returned.
            """
            fake_A, fake_B, idt_A, idt_B = output
            **#Save and look at png images of fake_A and fake_B here**

**Comment by tmabraham** [comment]
@rbunn80110 I am extremely sorry for the delay, I have been busy with various things but I am ramping up UPIT development now. 

There is a function to apply the model to new images:
https://tmabraham.github.io/UPIT/inference.cyclegan/#get_preds_cyclegan

This will apply the model to a folder of images in domain A to produce fake images in domain B. Does this suit your purpose?

Now that I think about it, I probably should add a way to generate fake_A images as well. I will do that ASAP. Hopefully these features meet your needs.

**Comment by tmabraham** [comment]
@rbunn80110 I added a `convert_to` argument for `get_preds_cyclegan` so you can select which direction you want to convert. Please let me know if you need any other inference functionality.

**Comment by tmabraham** [comment]
@rbunn80110 I haven't heard a response back from you, so I am closing the issue for now. Feel free to re-open the issue if you believe your question hasn't been answered.
