### ISSUE TITLE
Disable Identity Loss

### ISSUE THREAD

**Issue by hno2** [tmabraham/UPIT#17]
Hey, 
thanks for your awesome work.
If I want to set `l_idt` of the `CycleGANLoss` to zero, how would I do this? Can I pass this some argument to the `cycle_learner`? 
On a quick look this seems to be hardcoded in the `cycle_learner`, right ? 
So I would have to right "my own" `cycle_learner`?

Thanks for the answers to my - most likely - stupid questions!

**Comment by tmabraham** [comment]
@hno2 Thank you for your interest in my package! 

You should be able to change it after defining your `Learner` like this:
`learn.loss_func.l_idt = 0`

But I decided it might be best just to make my code more flexible, so I have added the `loss_func` argument to `cycle_learner`. Now you can pass in `loss_func=partial(CycleGANLoss, l_idt=0)` into `cycle_learner`. An example of this should be available at the end of this notebook:
https://github.com/tmabraham/UPIT/blob/master/nbs/03_train.cyclegan.ipynb

Does this resolve your question?

**Comment by hno2** [comment]
Yes, thats perfect and solves my problem. 
Thank you very much!
