### ISSUE TITLE
Documentation Mismatch on get_preds_cyclegan

### ISSUE THREAD

**Issue by hno2** [tmabraham/UPIT#18]
Hey there quick note,

there is a mismatch between the documentation and the code for suffix  `get_preds_cyclegan`. According to the documentation it is `png` but in the code the default value is `tif`.

I think I would also beneficial to check wether CUDA/GPU is available here, as inference also works well on a CPU (at least for me), but CUDA required here. What do you think?

**Comment by tmabraham** [comment]
Thanks for pointing out the mistake and the suggested feature. I have added it in my latest commit. Let me know if you have any questions!
