### ISSUE TITLE
Expose tfms in dataset generation

### ISSUE THREAD

**Issue by hno2** [tmabraham/UPIT#19]
Hey there, 

I think it would be a good idea to expose the `tfms` of the `Datasets` in the `get_dls`-Function, so users can set their own. https://github.com/tmabraham/UPIT/blob/c6c769cf8cedeec42865deddba26c2e413772303/upit/data/unpaired.py#L30

Same goes for `dataloaders` `batch_tfms`, (e.g. if I want to disable Flipping I have to rewrite the dataloaders)
 
https://github.com/tmabraham/UPIT/blob/c6c769cf8cedeec42865deddba26c2e413772303/upit/data/unpaired.py#L33

**Comment by tmabraham** [comment]
Hmmm, what would be some use-cases for this?

I am willing to consider adding `batch_tfms` as an argument to be able to include your own augmentations (I'd like to experiment with this too). However, I don't know if there is any reason to change the Dataset tfms.  Overall, I am trying to keep the dataloading as similar as possible to the original CycleGAN paper.

By the way, I appreciate your feedback and suggestions and I am curious if you are working on a CycleGAN-related project?

**Comment by hno2** [comment]
Hey Tanishq, 

thanks for your answer. I am actually working on a project with CycleGAN - it's about scene generation for autonomous driving. 
So I think my issue is mostly that flipping the scenes, might lead to wrong contexts being learned. I can of course just manually adapt the whole functions but I still think I might be (more) user friendly to expose the `tfms`. 
Anyway I am currently checking the influence of different augmentation (warping, color-changing) on the quality of the output, as I have not seen any extensive research in this field. 
So if you have any opinion or read something, just shoot me a note!

Thanks!

**Comment by tmabraham** [comment]
@hno2 So I finally quickly added batch_tfms and item_tfms arguments but I am not sure if this is the best way of doing this. Let me know what you think. Also, it's been 8 months so I don't know if you still are using my package but let me know if you are having any other issues. The development of this package will hopefully be more active now (currently working on multi-GPU training!)

**Comment by hno2** [comment]
Hey @tmabraham, thanks a lot. 
I will have a look asap.
